# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Thingsflow' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SnapKit', '~> 5.0.0'
  pod 'RxSwift', '~> 6.5.0'
  pod 'RxCocoa', '~> 6.5.0'

  # Pods for Thingsflow

  target 'ThingsflowTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ThingsflowUITests' do
    # Pods for testing
  end

end
